<?php

/**
 * -----------------------------------------------------------------------------
 * Generated 2020-10-31T02:21:09+08:00
 *
 * DO NOT EDIT THIS FILE DIRECTLY
 *
 * @item      api_keys.google.maps
 * @group     app
 * @namespace null
 * -----------------------------------------------------------------------------
 */
return [
    'server_timezone' => 'Asia/Manila',
    'api_keys' => [
        'google' => [
            'maps' => 'AIzaSyDd2WXpRnOihVXCRVfWqT82O2UOQOK1uEc',
        ],
    ],
];
