<?php

/**
 * -----------------------------------------------------------------------------
 * Generated 2020-11-04T21:13:50+08:00
 *
 * DO NOT EDIT THIS FILE DIRECTLY
 *
 * @item      seo.url_rewriting
 * @group     concrete
 * @namespace null
 * -----------------------------------------------------------------------------
 */
return [
    'version_installed' => '8.4.5',
    'version_db_installed' => '20180717000000',
    'misc' => [
        'login_redirect' => 'DESKTOP',
        'access_entity_updated' => 1603610841,
        'do_page_reindex_check' => false,
        'latest_version' => '8.4.5',
    ],
    'calendar' => [
        'topic_attribute' => 'event_categories',
    ],
    'cache' => [
        'blocks' => false,
        'assets' => false,
        'theme_css' => false,
        'overrides' => false,
        'pages' => '0',
        'full_page_lifetime' => 'default',
        'full_page_lifetime_value' => null,
        'clear' => [
            'thumbnails' => false,
        ],
    ],
    'theme' => [
        'compress_preprocessor_output' => false,
        'generate_less_sourcemap' => true,
    ],
    'seo' => [
        'redirect_to_canonical_url' => 0,
        'url_rewriting' => true,
    ],
];
