<?php

/**
 * -----------------------------------------------------------------------------
 * Generated 2021-09-18T00:33:29+08:00
 *
 * DO NOT EDIT THIS FILE DIRECTLY
 *
 * @item      cache.clear.thumbnails
 * @group     concrete
 * @namespace null
 * -----------------------------------------------------------------------------
 */
return [
    'version_installed' => '8.4.5',
    'version_db_installed' => '20180717000000',
    'misc' => [
        'login_redirect' => 'DESKTOP',
        'access_entity_updated' => 1603610841,
        'do_page_reindex_check' => false,
        'latest_version' => '8.4.5',
    ],
    'calendar' => [
        'topic_attribute' => 'event_categories',
    ],
    'cache' => [
        'blocks' => false,
        'assets' => false,
        'theme_css' => false,
        'overrides' => false,
        'pages' => '0',
        'full_page_lifetime' => 'default',
        'full_page_lifetime_value' => null,
        'clear' => [
            'thumbnails' => true,
        ],
    ],
    'theme' => [
        'compress_preprocessor_output' => false,
        'generate_less_sourcemap' => true,
    ],
    'seo' => [
        'redirect_to_canonical_url' => 0,
        'url_rewriting' => true,
    ],
    'email' => [
        'default' => [
            'name' => 'MVBC',
            'address' => 'info@mvbc.com.ph',
        ],
        'forgot_password' => [
            'name' => '',
            'address' => '',
        ],
        'form_block' => [
            'address' => 'info@mvbc.com.ph',
        ],
        'register_notification' => [
            'address' => '',
        ],
        'validate_registration' => [
            'name' => '',
            'address' => '',
        ],
        'workflow_notification' => [
            'name' => '',
            'address' => '',
        ],
    ],
    'spam' => [
        'notify_email' => '',
    ],
];
