<?php

/**
 * -----------------------------------------------------------------------------
 * Generated 2020-11-04T21:52:02+08:00
 *
 * DO NOT EDIT THIS FILE DIRECTLY
 *
 * @item      sites.default.seo.canonical_tag.enabled
 * @group     site
 * @namespace null
 * -----------------------------------------------------------------------------
 */
return [
    'sites' => [
        'default' => [
            'name' => 'MVBC',
            'seo' => [
                'canonical_url' => '',
                'canonical_url_alternative' => '',
                'canonical_tag' => [
                    'enabled' => true,
                ],
            ],
        ],
    ],
];
