<?php

/**
 * -----------------------------------------------------------------------------
 * Generated 2020-10-25T15:05:56+08:00
 *
 * DO NOT EDIT THIS FILE DIRECTLY
 *
 * @item      sites.default.name
 * @group     site
 * @namespace null
 * -----------------------------------------------------------------------------
 */
return [
    'sites' => [
        'default' => [
            'name' => 'MVBC',
        ],
    ],
];
